version: '2.3'
services:
  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    environment:
      - POSTGRES_USER=franklin
      - POSTGRES_PASSWORD=franklin
      - POSTGRES_DB=franklin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "franklin"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  franklin:
    image: quay.io/azavea/franklin:latest
    depends_on:
      database:
        condition: service_healthy
    command: ["serve", "--with-transactions"]
    volumes:
      - ./:/opt/franklin/
    environment:
      - ENVIRONMENT=development
      - POSTGRES_URL=jdbc:postgresql://database.service.internal/
      - POSTGRES_NAME=franklin
      - POSTGRES_USER=franklin
      - POSTGRES_PASSWORD=franklin
      - AWS_REGION=us-east-1
    links:
      - database:database.service.internal
    ports:
      - "9090:9090"
